version: '3.8'

services:
  cc_tagger_100:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: cc_tagger_100
    volumes:
      - /home/ubuntu/cc_tagging_100/cc_articles_tagger/processed_doc_id.txt:/app/processed_doc_id.txt
    networks:
      - cc_tagger_network_100
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 3g
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

networks:
  cc_tagger_network_100:
    driver: bridge
