version: '3.8'

services:
  cc_tagger_45:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: cc_tagger_45
    cpus: 0.50
    mem_limit: 3g
    # restart: always
    volumes:
          - /home/azureuser/cc_tagging_45/cc_articles_tagger/processed_doc_id.txt:/app/processed_doc_id.txt
    networks:
    - cc_tagger_network_45
    deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['1'] # Specify 2 to use both GPUs
            capabilities: [ gpu ]


networks:
  cc_tagger_network_45:
    driver: bridge
