
# FROM python:3.11
# WORKDIR /app_
# COPY . /app_/
# RUN pip install -r requirements.txt
# CMD ["python3","main.py"]

# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /app_

# Copy only requirements.txt first to leverage Docker cache
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Command to run the application
CMD ["python3", "main.py"]

# FROM nvidia/cuda:12.3.1-base-ubuntu22.04
# RUN apt-get update && \
#     apt-get install -y python3-pip libpq-dev python3-dev && \
#     rm -rf /var/lib/apt/lists/*
# WORKDIR /worker
# COPY . /worker/
# RUN pip install --no-cache-dir -r requirements.txt
# CMD ["python3", "main.py"]
